// Generated by CoffeeScript 1.9.1
(function() {
  var apn, apnConnection, device, gcm;

  apn = require('apn');

  gcm = require('gcm');

  apnConnection = new apn.Connection({});

  device = new apn.Device('token');

}).call(this);
