// Generated by CoffeeScript 1.9.1
(function() {
  var config;

  process.env.NODE_ENV = process.env.NODE_ENV || 'development';

  config = require('./env/' + process.env.NODE_ENV);

  module.exports = config;

}).call(this);
