// Generated by CoffeeScript 1.9.1
(function() {
  var development;

  development = {
    mongoURL: 'mongodb://localhost:27017/teams',
    port: 7500,
    ip: '127.0.0.1'
  };

  module.exports = development;

}).call(this);
