// Generated by CoffeeScript 1.9.1
(function() {
  var production;

  production = {
    mongoURL: 'mongodb://localhost:27017/local',
    port: 7500,
    ip: '172.18.0.30'
  };

  module.exports = production;

}).call(this);
